=== angryzor/furry-octo-hipster/trunk/Advanced installer/HUD Installer/HUD Installer/installlayout.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://www.fpsbanana.com/guis/23833/installlayout" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="InstallLayout">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="Tab">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Title" type="xs:string" />
              <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="Checkbox">
                  <xs:complexType>
                    <xs:sequence>
                      <xs:element name="Id" type="xs:string" />
                      <xs:element name="Component" type="xs:string" />
                    </xs:sequence>
                  </xs:complexType>
                </xs:element>
                <xs:element name="Choice">
                  <xs:complexType>
                    <xs:sequence>
                      <xs:element name="Id" type="xs:string" />
                      <xs:element name="Label" type="xs:string" />
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="Category" type="xs:string" />
                        <xs:element name="Component" type="xs:string" />
                      </xs:choice>
                    </xs:sequence>
                  </xs:complexType>
                </xs:element>
              </xs:choice>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== angryzor/furry-octo-hipster/trunk/Advanced installer/HUD Installer/HUD Installer/installlayout.xml
<?xml version="1.0" encoding="utf-8" ?>
<InstallLayout xmlns="http://www.fpsbanana.com/guis/23833/installlayout" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.fpsbanana.com/guis/23833/installlayout installlayout.xsd">
  <Tab>
    <Title>Death Icons</Title>
    <Choice>
      <Id>rocket</Id>
      <Label>Rocketlauncher</Label>
      <Category>death notices/rocket</Category>
    </Choice>
    <Choice>
      <Id>sniperrifle</Id>
      <Label>Sniper Rifle</Label>
      <Category>death notices/sniperrifle</Category>
    </Choice>
  </Tab>
  <Tab>
    <Title>Engi HUD</Title>
    <Checkbox>
      <Id>engi_hud</Id>
      <Component>engi_hud</Component>
    </Checkbox>
  </Tab>
</InstallLayout>
