=== angryzor/furry-octo-hipster/trunk/Advanced installer/HUD Installer/HUD Installer/installdata.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://www.fpsbanana.com/guis/23833/installdata" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="InstallData">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="Component">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Id" type="xs:string" />
              <xs:element name="Name" type="xs:string" />
              <xs:element name="Author" type="xs:string" />
              <xs:element minOccurs="0" name="Image" type="xs:string" />
              <xs:element minOccurs="0" name="Category" type="xs:string" />
              <xs:element minOccurs="0" maxOccurs="unbounded" name="Tag" type="xs:string" />
              <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="Depend" type="xs:string" />
                <xs:element name="TagConflict" type="xs:string" />
                <xs:element name="CategoryConflict" type="xs:string" />
                <xs:element name="ComponentConflict" type="xs:string" />
                <xs:element name="File" type="xs:string" />
                <xs:element name="Patch">
                  <xs:complexType>
                    <xs:simpleContent>
                      <xs:extension base="xs:string">
                        <xs:attribute name="file" type="xs:string" use="required" />
                      </xs:extension>
                    </xs:simpleContent>
                  </xs:complexType>
                </xs:element>
              </xs:choice>
            </xs:sequence>
            <xs:attribute name="hidden" type="xs:string" use="optional" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== angryzor/furry-octo-hipster/trunk/installtools/installdata.xml
<?xml version="1.0" encoding="utf-8" ?>
<InstallData xmlns="http://www.fpsbanana.com/guis/23833/installdata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.fpsbanana.com/guis/23833/installdata installdata.xsd">
  <!-- *** Basics: the plugin ***** -->
  <Component>
    <Id>plugin</Id>
    <Name>HUD Extensions Plugin DLL (needed for a lot of the HUD enhancements)</Name>
    <Author>angryzor</Author>
    <Image>plugin.png</Image>
    <Depend>plugin</Depend>
    <File>addons</File>
  </Component>

  <!-- *** Engi hud *************** -->
  <Component>
    <Id>engi_hud</Id>
    <Name>Engineer HUD</Name>
    <Author>angryzor</Author>
    <Image>engi_hud.png</Image>
    <Depend>plugin</Depend>
    <File>resource</File>
    <File>materials\vgui\logos\visual_improve_hud\eng_status_area*.*</File>
    <File>materials\vgui\logos\visual_improve_hud\hud_obj_status*.*</File>
    <Patch file="mod_textures">mt_engi_hud.txt</Patch>
  </Component>


  <!-- *** angryzor death icons *** -->
  <!-- BEGIN old unlocks -->
  <Component>
    <Id>dn_fan_1</Id>
    <Name>Force-a-Nature 1</Name>
    <Author>angryzor</Author>
    <Image>dn_fan_1.png</Image>
    <Category>death notices/fan</Category>
    <CategoryConflict>death notices/fan</CategoryConflict>
    <Depend>plugin</Depend>
    <File>materials\vgui\logos\visual_improve_hud\d_force_a_nature.*</File>
    <Patch file="mod_textures">mt_dn_fan_1.txt</Patch>
  </Component>
  <Component>
    <Id>dn_blutsauger_1</Id>
    <Name>Blutsauger 1</Name>
    <Author>angryzor</Author>
    <Image>dn_blutsauger_1.png</Image>
    <Category>death notices/blutsauger</Category>
    <CategoryConflict>death notices/blutsauger</CategoryConflict>
    <Depend>plugin</Depend>
    <File>materials\vgui\logos\visual_improve_hud\d_blutsauger.*</File>
    <Patch file="mod_textures">mt_dn_blutsauger_1.txt</Patch>
  </Component>
  <Component>
    <Id>dn_backburner_1</Id>
    <Name>Backburner 1</Name>
    <Author>angryzor</Author>
    <Image>dn_backburner_1.png</Image>
    <Category>death notices/backburner</Category>
    <CategoryConflict>death notices/backburner</CategoryConflict>
    <Depend>plugin</Depend>
    <File>materials\vgui\logos\visual_improve_hud\d_backburner.*</File>
    <Patch file="mod_textures">mt_dn_backburner_1.txt</Patch>
  </Component>
  <Component>
    <Id>dn_backburner_back_1</Id>
    <Name>Backburner in back 1</Name>
    <Author>angryzor</Author>
    <Image>dn_backburner_back_1.png</Image>
    <Category>death notices/backburner_back</Category>
    <CategoryConflict>death notices/backburner_back</CategoryConflict>
    <Depend>plugin</Depend>
    <File>materials\vgui\logos\visual_improve_hud\d_backburner_back.*</File>
    <Patch file="mod_textures">mt_dn_backburner_back_1.txt</Patch>
  </Component>
  <Component>
    <Id>dn_natascha_1</Id>
    <Name>Natascha 1</Name>
    <Author>angryzor</Author>
    <Image>dn_natascha_1.png</Image>
    <Category>death notices/natascha</Category>
    <CategoryConflict>death notices/natascha</CategoryConflict>
    <Depend>plugin</Depend>
    <File>materials\vgui\logos\visual_improve_hud\d_natascha.*</File>
    <Patch file="mod_textures">mt_dn_natascha_1.txt</Patch>
  </Component>
  <!-- END old unlocks -->

  <!-- BEGIN new unlocks -->
  <Component>
    <Id>dn_paintrain_1</Id>
    <Name>Pain Train 1</Name>
    <Author>angryzor</Author>
    <Image>dn_paintrain_1.png</Image>
    <Category>death notices/paintrain</Category>
    <CategoryConflict>death notices/paintrain</CategoryConflict>
    <File>materials\vgui\logos\visual_improve_hud\d_paintrain.*</File>
    <Patch file="mod_textures">mt_dn_paintrain_1.txt</Patch>
  </Component>
  <Component>
    <Id>dn_sledgehammer_1</Id>
    <Name>Pain Train 1</Name>
    <Author>angryzor</Author>
    <Image>dn_sledgehammer_1.png</Image>
    <Category>death notices/sledgehammer</Category>
    <CategoryConflict>death notices/sledgehammer</CategoryConflict>
    <File>materials\vgui\logos\visual_improve_hud\d_sledgehammer.*</File>
    <Patch file="mod_textures">mt_dn_sledgehammer_1.txt</Patch>
  </Component>
  <Component>
    <Id>dn_telefrag_1</Id>
    <Name>Telefrag 1</Name>
    <Author>angryzor</Author>
    <Image>dn_telefrag_1.png</Image>
    <Category>death notices/telefrag</Category>
    <CategoryConflict>death notices/telefrag</CategoryConflict>
    <Depend>plugin</Depend>
    <Depend>dn_dement_tex_1</Depend>
    <Patch file="mod_textures">mt_dn_telefrag_1.txt</Patch>
  </Component>
  <!-- END new unlocks -->

  <!-- Completely new icons -->
  <Component>
    <Id>dn_building_destroy_1</Id>
    <Name>Destroy own building 1</Name>
    <Author>angryzor</Author>
    <Image>dn_building_destroy_1.png</Image>
    <Category>death notices/building_destroy</Category>
    <CategoryConflict>death notices/building_destroy</CategoryConflict>
    <Depend>plugin</Depend>
    <Depend>dn_dement_tex_1</Depend>
    <Patch file="mod_textures">mt_dn_building_destroy_1.txt</Patch>
  </Component>


  <!-- *** Dement death icons ***** -->
  <!-- Textures -->
  <Component hidden="true">
    <Id>dn_dement_tex_1</Id>
    <Name>Dement's textures for death icons</Name>
    <Author>Dement</Author>
    <File>materials\vgui\logos\visual_improve_hud\dement_1</File>
  </Component>

  <!-- BEGIN improves -->
  <Component>
    <Id>dn_rocket_1</Id>
    <Name>Rocketlauncher 1</Name>
    <Author>Dement</Author>
    <Image>dn_rocket_1.png</Image>
    <Category>death notices/rocket</Category>
    <CategoryConflict>death notices/rocket</CategoryConflict>
    <Depend>dn_dement_tex_1</Depend>
    <Patch file="mod_textures">mt_dn_rocket_1.txt</Patch>
  </Component>
  <Component>
    <Id>dn_sniperrifle_1</Id>
    <Name>Sniper Rifle 1</Name>
    <Author>Dement</Author>
    <Image>dn_sniperrifle_1.png</Image>
    <Category>death notices/sniperrifle</Category>
    <CategoryConflict>death notices/sniperrifle</CategoryConflict>
    <Depend>dn_dement_tex_1</Depend>
    <Patch file="mod_textures">mt_dn_sniperrifle_1.txt</Patch>
  </Component>
  <Component>
    <Id>dn_syringegun_1</Id>
    <Name>Syringe Gun 1</Name>
    <Author>Dement</Author>
    <Image>dn_syringegun_1.png</Image>
    <Category>death notices/syringegun</Category>
    <CategoryConflict>death notices/syringegun</CategoryConflict>
    <Depend>dn_dement_tex_1</Depend>
    <Patch file="mod_textures">mt_dn_syringegun_1.txt</Patch>
  </Component>
  <Component>
    <Id>dn_gloves_1</Id>
    <Name>Gloves 1</Name>
    <Author>Dement</Author>
    <Image>dn_gloves_1.png</Image>
    <Category>death notices/gloves</Category>
    <CategoryConflict>death notices/gloves</CategoryConflict>
    <Depend>dn_dement_tex_1</Depend>
    <Patch file="mod_textures">mt_dn_gloves_1.txt</Patch>
  </Component>
  <Component>
    <Id>dn_sticky_resistance_1</Id>
    <Name>Scottish Resistance 1</Name>
    <Author>Dement</Author>
    <Image>dn_sticky_resistance_1.png</Image>
    <Category>death notices/sticky_resistance</Category>
    <CategoryConflict>death notices/sticky_resistance</CategoryConflict>
    <Depend>dn_dement_tex_1</Depend>
    <Patch file="mod_textures">mt_dn_sticky_resistance_1.txt</Patch>
  </Component>
  <Component>
    <Id>dn_backstab_1</Id>
    <Name>Backstab 1</Name>
    <Author>Dement</Author>
    <Image>dn_backstab_1.png</Image>
    <Category>death notices/backstab</Category>
    <CategoryConflict>death notices/backstab</CategoryConflict>
    <Depend>dn_dement_tex_1</Depend>
    <Patch file="mod_textures">mt_dn_backstab_1.txt</Patch>
  </Component>
  <Component>
    <Id>dn_headshot_1</Id>
    <Name>Headshot 1</Name>
    <Author>Dement</Author>
    <Image>dn_headshot_1.png</Image>
    <Category>death notices/headshot</Category>
    <CategoryConflict>death notices/headshot</CategoryConflict>
    <Depend>dn_dement_tex_1</Depend>
    <Patch file="mod_textures">mt_dn_headshot_1.txt</Patch>
  </Component>
  <Component>
    <Id>dn_huntsman_headshot_1</Id>
    <Name>Huntsman headshot 1</Name>
    <Author>Dement</Author>
    <Image>dn_huntsman_headshot_1.png</Image>
    <Category>death notices/huntsman_headshot</Category>
    <CategoryConflict>death notices/huntsman_headshot</CategoryConflict>
    <Depend>dn_dement_tex_1</Depend>
    <Patch file="mod_textures">mt_dn_huntsman_headshot_1.txt</Patch>
  </Component>
  <Component>
    <Id>dn_ambassador_1</Id>
    <Name>Ambassador 1</Name>
    <Author>Dement</Author>
    <Image>dn_ambassador_1.png</Image>
    <Category>death notices/ambassador</Category>
    <CategoryConflict>death notices/ambassador</CategoryConflict>
    <Depend>dn_dement_tex_1</Depend>
    <Patch file="mod_textures">mt_dn_ambassador_1.txt</Patch>
  </Component>
  <Component>
    <Id>dn_rocketlauncher_directhit_1</Id>
    <Name>Direct Hit 1</Name>
    <Author>Dement</Author>
    <Image>dn_rocketlauncher_directhit_1.png</Image>
    <Category>death notices/rocketlauncher_directhit</Category>
    <CategoryConflict>death notices/rocketlauncher_directhit</CategoryConflict>
    <Depend>dn_dement_tex_1</Depend>
    <Patch file="mod_textures">mt_dn_rocketlauncher_directhit_1.txt</Patch>
  </Component>
  <Component>
    <Id>dn_shotgun_1</Id>
    <Name>Shotgun 1</Name>
    <Author>Dement</Author>
    <Image>dn_shotgun_1.png</Image>
    <Category>death notices/shotgun</Category>
    <CategoryConflict>death notices/shotgun</CategoryConflict>
    <Depend>dn_dement_tex_1</Depend>
    <Patch file="mod_textures">mt_dn_shotgun_1.txt</Patch>
  </Component>
  <Component>
    <Id>dn_pistol_1</Id>
    <Name>Pistol 1</Name>
    <Author>Dement</Author>
    <Image>dn_pistol_1.png</Image>
    <Category>death notices/pistol</Category>
    <CategoryConflict>death notices/pistol</CategoryConflict>
    <Depend>dn_dement_tex_1</Depend>
